#import '~/queries/fragments/EditorBlock.fragment.gql';
#import '~/queries/fragments/CoreImage.fragment.gql';

fragment CoreGallery on CoreGallery {
  ...EditorBlock
  innerBlocks {
    ...CoreImage
  }
}
