#import '~/queries/fragments/MediaItem.fragment.gql';

fragment NodeWithFeaturedImageToMediaItemConnectionEdge on NodeWithFeaturedImageToMediaItemConnectionEdge {
  cursor
  node {
    ...MediaItem
  }
}
