#import '~/queries/fragments/NodeWithFeaturedImageToMediaItemConnectionEdge.fragment.gql';

fragment NodeWithFeaturedImage on NodeWithFeaturedImage {
  featuredImage { 
    ...NodeWithFeaturedImageToMediaItemConnectionEdge
  }
  featuredImageDatabaseId
  featuredImageId
  id
}