fragment CoreGallery on CoreGallery {
  attributes {
    align
    allowResize
    anchor
    backgroundColor
    caption
    className
    columns
    fixedHeight
    gradient
    ids
    imageCrop
    layout
    linkTarget
    linkTo
    lock
    metadata
    randomOrder
    shortCodeTransforms
    style
    images {
      alt
      caption
      fullUrl
      id
      link
      url
    }
  }
}
