#import '~/queries/fragments/EditorBlock.fragment.gql';

fragment CoreImage on CoreImage {
  ...EditorBlock
  attributes {
    align
    alt
    anchor
    aspectRatio
    borderColor
    caption
    className
    cssClassName
    height
    href
    id
    linkClass
    linkDestination
    linkTarget
    lock
    rel
    scale
    sizeSlug
    src
    style
    title
    url
    width
  }
}
