fragment CoreQuote on CoreQuote {
  attributes {
    align
    anchor
    backgroundColor
    citation
    className
    cssClassName
    fontFamily
    fontSize
    gradient
    layout
    lock
    metadata
    style
    textColor
    value
  }
}
