#import '~/queries/fragments/CoreButton.fragment.gql';
#import '~/queries/fragments/CoreGallery.fragment.gql';
#import '~/queries/fragments/CoreImage.fragment.gql';
#import '~/queries/fragments/CoreParagraph.fragment.gql';
#import '~/queries/fragments/CoreQuote.fragment.gql';

fragment EditorBlock on EditorBlock {
  apiVersion
  blockEditorCategoryName
  clientId
  cssClassNames
  isDynamic
  name
  parentClientId
  renderedHtml
  ...CoreButton
  ...CoreGallery
  ...CoreImage
  ...CoreParagraph
  ...CoreQuote
}
