#import "~/queries/fragments/Page.fragment.gql"
#import "~/queries/fragments/NodeWithFeaturedImage.fragment.gql"

query Pages($limit: Int = 10) {
  pages(first: $limit) {
    nodes {
      ...Page
      ...NodeWithFeaturedImage
    }
  }
}
